<a href="https://colab.research.google.com/github/146790g/Mode-Of-Action-Data/blob/master/MOA_MLP_2_Model_Fitting_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mode of Action 

##Mechanisms of Action (MoA) Prediction
##Can you improve the algorithm that classifies drugs based on their biological activity?

#（その２： Model Fitting - No. 3 ）

https://machinelearningmastery.com/multi-label-classification-with-deep-learning/



In [ ]:
%tensorflow_version 2.x

In [ ]:
%pwd
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
!ls -lh '/content/gdrive/My Drive/Colab Notebooks/MOA/data'

total 649M
-rw------- 1 root root 3.2M Sep  2 06:04 sample_submission.csv
-rw------- 1 root root  25M Sep  2 06:04 test_features.csv
-rw------- 1 root root 150M Sep  2 06:04 train_features.csv
-rw------- 1 root root  19M Sep  2 06:04 train_targets_nonscored.csv
-rw------- 1 root root 9.7M Sep  2 06:04 train_targets_scored.csv
-rw------- 1 root root  48M Nov  4 11:42 X_fp_test
-rw------- 1 root root 285M Nov  4 11:42 X_fp_train
-rw------- 1 root root  38M Nov  4 11:42 y
-rw------- 1 root root  74M Nov  4 11:42 y0


# Module Load

In [ ]:
import warnings
warnings.filterwarnings("ignore")

# Adding iterative-stratification 
# Select add data from the right menu and search for iterative-stratification, then add it to your kernel.
import sys
sys.path.append('../input/iterative-stratification/iterative-stratification-master')
#from iterstrat.ml_stratifiers import MultilabelStratifiedKFold


from time import time
import datetime
import gc
import pickle

import numpy as np
import pandas as pd 

# ML tools 
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, EarlyStopping
import tensorflow as tf 
from tensorflow.keras import layers
import tensorflow.keras.backend as K
from sklearn.metrics import log_loss
from sklearn.model_selection import KFold
from tensorflow_addons.layers import WeightNormalization
# Setting random seeds
np.random.seed(42)
tf.random.set_seed(42)

# Visualization tools
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style('white')
sns.set(font_scale=1.2)




# Data Load

In [ ]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/content/gdrive/My Drive/Colab Notebooks/MOA/data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



data_dir = '/content/gdrive/My Drive/Colab Notebooks/MOA/data'

/content/gdrive/My Drive/Colab Notebooks/MOA/data/test_features.csv
/content/gdrive/My Drive/Colab Notebooks/MOA/data/sample_submission.csv
/content/gdrive/My Drive/Colab Notebooks/MOA/data/train_features.csv
/content/gdrive/My Drive/Colab Notebooks/MOA/data/train_targets_scored.csv
/content/gdrive/My Drive/Colab Notebooks/MOA/data/train_targets_nonscored.csv
/content/gdrive/My Drive/Colab Notebooks/MOA/data/X_fp_train
/content/gdrive/My Drive/Colab Notebooks/MOA/data/X_fp_test
/content/gdrive/My Drive/Colab Notebooks/MOA/data/y0
/content/gdrive/My Drive/Colab Notebooks/MOA/data/y


In [ ]:
with open(os.path.join(data_dir,'X_fp_train'),'rb') as web:
  X_fp_train=pickle.load(web)

   
with open(os.path.join(data_dir,'X_fp_test'),'rb') as web:
  X_fp_test=pickle.load(web)
    
with open(os.path.join(data_dir,'y'),'rb') as web:
  y=pickle.load(web)
    
with open(os.path.join(data_dir,'y0'),'rb') as web:
  y0=pickle.load(web)
    
X_fp_train=X_fp_train.drop('sig_id',axis=1)
X_fp_test=X_fp_test.drop('sig_id',axis=1)
y=y.drop('sig_id',axis=1)
y0=y0.drop('sig_id',axis=1)

display(X_fp_train)
print(X_fp_train.shape)
print(type(X_fp_train))

display(X_fp_test)
print(X_fp_test.shape)

display(y)
print(y.shape)

display(y0)
print(y0.shape)


feature_0  feature_1  feature_2  ...  cp_type  cp_time  cp_dose
0       1.134849   0.907687  -0.416385  ...        0        1        0
1       0.119282   0.681738   0.272399  ...        0        3        0
2       0.779973   0.946463   1.425350  ...        0        2        0
3      -0.734910  -0.274641  -0.438509  ...        0        2        0
4      -0.452718  -0.477513   0.972316  ...        0        3        1
...          ...        ...        ...  ...      ...      ...      ...
23809   0.209361  -0.022389  -0.235888  ...        0        1        1
23810  -1.911021   0.587228  -0.588417  ...        0        1        1
23811   0.525149   0.631225   0.288173  ...        1        2        1
23812   0.816407   0.417618   0.431631  ...        0        1        0
23813  -1.243096   1.567730  -0.269573  ...        0        3        0

[23814 rows x 1563 columns]

(23814, 1563)
<class 'pandas.core.frame.DataFrame'>


feature_0  feature_1  feature_2  ...  cp_type  cp_time  cp_dose
0     -0.755294   0.214796  -0.774511  ...        0        1        0
1     -0.186773   0.374643   1.176402  ...        0        3        0
2      0.351229  -0.155308  -0.613250  ...        1        1        0
3      0.705453   0.318216   0.375618  ...        0        1        1
4     -0.508836  -1.512891   1.649608  ...        0        2        0
...         ...        ...        ...  ...      ...      ...      ...
3977   0.675950  -0.699428   2.335959  ...        0        1        0
3978  -0.825801  -0.297793   1.984731  ...        0        1        0
3979  -0.509991  -0.176776   0.253602  ...        0        3        0
3980  -1.627922  -2.062092  -0.623309  ...        0        2        1
3981  -0.705098   0.473736   0.314137  ...        0        3        0

[3982 rows x 1563 columns]

(3982, 1563)


5-alpha_reductase_inhibitor  ...  wnt_inhibitor
0                                0  ...              0
1                                0  ...              0
2                                0  ...              0
3                                0  ...              0
4                                0  ...              0
...                            ...  ...            ...
23809                            0  ...              0
23810                            0  ...              0
23811                            0  ...              0
23812                            0  ...              0
23813                            0  ...              0

[23814 rows x 206 columns]

(23814, 206)


abc_transporter_expression_enhancer  ...  xiap_inhibitor
0                                        0  ...               0
1                                        0  ...               0
2                                        0  ...               0
3                                        0  ...               0
4                                        0  ...               0
...                                    ...  ...             ...
23809                                    0  ...               0
23810                                    0  ...               0
23811                                    0  ...               0
23812                                    0  ...               0
23813                                    0  ...               0

[23814 rows x 402 columns]

(23814, 402)


# Define Model

In [ ]:
X_fp_train.shape[1],y.shape[1]


(1563, 206)

In [ ]:
import tensorflow as tf
import numpy as np
from keras.models import Model
from keras.layers import Input, Lambda,Activation,Dropout,Flatten,Dense
import keras.backend as K
from tensorflow import keras

import tensorflow as tf
import numpy as np
from keras.models import Model
from keras.layers import Input, Lambda,Activation,Dropout,Flatten,Dense,BatchNormalization
import keras.backend as K
from tensorflow import keras,losses

p_min = 0.001
p_max = 0.999

from tensorflow.keras import regularizers

def logloss(y_true, y_pred):
    y_pred = tf.clip_by_value(y_pred,p_min,p_max)
    return -K.mean(y_true*K.log(y_pred) + (1-y_true)*K.log(1-y_pred))

def create_model(num_cols, hid_layers, activations, dropout_rate, lr, num_cols_y):
   
    inp1 = tf.keras.layers.Input(shape = (num_cols, ))
    x1 = tf.keras.layers.BatchNormalization()(inp1)

    for i, units in enumerate(hid_layers):
        x1 = tf.keras.layers.Dense(units, activation=activations[i])(x1)
        x1 = tf.keras.layers.Dropout(dropout_rate[i])(x1)
        x1 = tf.keras.layers.BatchNormalization()(x1)
    
    x1 = tf.keras.layers.Dense(num_cols_y,activation='sigmoid')(x1)
    model = tf.keras.models.Model(inputs= inp1, outputs= x1)
    
    model.compile(optimizer = 'adam',
                 loss='binary_crossentropy', metrics=['accuracy'])
    
    return model 

In [ ]:
feats = np.arange(0,1563,1)
inp_size = int(np.ceil(1* len(feats)))
print(inp_size)

1563


In [ ]:
 hid_layers = [[512, 768, 896],[384, 640, 1024],[768,768,896],[512, 384, 1024],
              [512, 640, 640], [640, 896, 1024], [256,640,896],[512,512,768],
              [512, 384, 896],[512,768,768]]

dropout_rate = [[0.65,0.35,0.35],[0.65,0.35,0.45],[0.7,0.4,0.4],[0.65,0.35,0.45],
                [0.65,0.35,0.45],[0.7,0.3,0.45],[0.7,0.35,0.4],[0.7,0.4,0.4],
               [0.7, 0.3, 0.4],[0.65, 0.3, 0.4]]

activations = [['elu', 'swish', 'selu'], ['selu','swish','selu'], ['selu','swish','selu'],
              ['selu','swish','elu'],['selu','swish','elu'],['elu','swish','selu'],
               ['selu','swish','elu'],['selu','elu','selu'],['selu','swish','selu'],
               ['selu','swish','elu']]

lr = [0.002989447175078026,0.003478591117397657,0.0033564715716489766,0.00377940659516057,
      0.00308613410674138,0.002893435735413818,0.003352025985912316,
      0.0037675761105464426, 0.0030559926758757876, 0.0040360434306992285]

feats = np.arange(0,1563,1)
inp_size = int(np.ceil(1* len(feats)))

model=create_model(1563,hid_layers[0], activations[0], dropout_rate[0], lr[0],206)

model.summary()


Model: "functional_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 1563)]            0         
_________________________________________________________________
batch_normalization_24 (Batc (None, 1563)              6252      
_________________________________________________________________
dense_24 (Dense)             (None, 512)               800768    
_________________________________________________________________
dropout_18 (Dropout)         (None, 512)               0         
_________________________________________________________________
batch_normalization_25 (Batc (None, 512)               2048      
_________________________________________________________________
dense_25 (Dense)             (None, 768)               393984    
_________________________________________________________________
dropout_19 (Dropout)         (None, 768)             

In [ ]:
results = list()
n_inputs, n_outputs = X.shape[1], y.shape[1]
	
	# define evaluation procedure
	#cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

X=X_fp_train2.astype('float64').values
y_np=y.astype('float64').values
  
kf=KFold(n_splits=4,shuffle=True,random_state=123)
 
tr_idx,var_idx = list(kf.split(X))[0]

tr_x,va_x = X[tr_idx],X[var_idx]
tr_y,va_y = y_np[tr_idx],y_np[var_idx]

display(tr_x)
print(tr_x.shape)

display(va_x)
print(va_x.shape)

display(tr_y)
print(tr_y.shape)

display(va_y)
print(va_y.shape)




array([[ 1.13484916,  0.90768744, -0.41638451, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.11928153,  0.68173822,  0.27239921, ...,  0.        ,
         3.        ,  0.        ],
       [ 0.77997254,  0.94646298,  1.42534985, ...,  0.        ,
         2.        ,  0.        ],
       ...,
       [ 0.52514873,  0.63122535,  0.28817292, ...,  1.        ,
         2.        ,  1.        ],
       [ 0.8164071 ,  0.4176183 ,  0.43163123, ...,  0.        ,
         1.        ,  0.        ],
       [-1.24309611,  1.56773029, -0.26957347, ...,  0.        ,
         3.        ,  0.        ]])

(17860, 1563)


array([[-0.07723442,  0.45386242, -0.79980709, ...,  0.        ,
         2.        ,  1.        ],
       [ 0.56154044,  2.15639416, -1.71022872, ...,  0.        ,
         3.        ,  0.        ],
       [-0.18992414, -0.20388731, -0.95615965, ...,  0.        ,
         2.        ,  0.        ],
       ...,
       [ 2.0751076 ,  0.74660291,  1.40922027, ...,  0.        ,
         3.        ,  1.        ],
       [-0.55651655, -1.28373779,  0.84598153, ...,  0.        ,
         2.        ,  0.        ],
       [-1.9110206 ,  0.58722771, -0.58841728, ...,  0.        ,
         1.        ,  1.        ]])

(5954, 1563)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

(17860, 206)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

(5954, 206)


In [ ]:
model=create_model(1563,hid_layers[0], activations[0], dropout_rate[0], lr[0],206)
model.summary()



Model: "functional_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 1563)]            0         
_________________________________________________________________
batch_normalization_28 (Batc (None, 1563)              6252      
_________________________________________________________________
dense_28 (Dense)             (None, 512)               800768    
_________________________________________________________________
dropout_21 (Dropout)         (None, 512)               0         
_________________________________________________________________
batch_normalization_29 (Batc (None, 512)               2048      
_________________________________________________________________
dense_29 (Dense)             (None, 768)               393984    
_________________________________________________________________
dropout_22 (Dropout)         (None, 768)             

In [ ]:
history=model.fit(
    tr_x,
    tr_y,
    epochs=100,
    batch_size=10000,
    verbose=1,
    validation_data=(
        va_x,va_y
    ))

Epoch 1/100
2/2 [==============================] - 0s 90ms/step - loss: 0.0131 - accuracy: 0.1918 - val_loss: 0.0155 - val_accuracy: 0.1213
Epoch 2/100
2/2 [==============================] - 0s 87ms/step - loss: 0.0130 - accuracy: 0.1947 - val_loss: 0.0155 - val_accuracy: 0.1204
Epoch 3/100
2/2 [==============================] - 0s 92ms/step - loss: 0.0131 - accuracy: 0.1918 - val_loss: 0.0155 - val_accuracy: 0.1196
Epoch 4/100
2/2 [==============================] - 0s 93ms/step - loss: 0.0130 - accuracy: 0.1944 - val_loss: 0.0155 - val_accuracy: 0.1189
Epoch 5/100
2/2 [==============================] - 0s 92ms/step - loss: 0.0130 - accuracy: 0.1946 - val_loss: 0.0155 - val_accuracy: 0.1194
Epoch 6/100
2/2 [==============================] - 0s 91ms/step - loss: 0.0129 - accuracy: 0.1963 - val_loss: 0.0155 - val_accuracy: 0.1191
Epoch 7/100
2/2 [==============================] - 0s 86ms/step - loss: 0.0129 - accuracy: 0.1978 - val_loss: 0.0155 - val_accuracy: 0.1192
Epoch 8/100
2/2 [===

In [ ]:
def evaluate_model(X, y):
	results = list()
	n_inputs, n_outputs = X.shape[1], y.shape[1]
	
	# define evaluation procedure
	#cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
  
	kf=KFold(n_splits=4,shuffle=True,random_state=123)

	# enumerate folds
	for train_ix, test_ix in cv.split(X):
		# prepare data
		X_train, X_test = X[train_ix], X[test_ix]
		y_train, y_test = y[train_ix], y[test_ix]
		# define model
		model = model=create_model(1563,hid_layers[0], activations[0], dropout_rate[0], lr[0],206)
		# fit model
		model.fit(X_train, y_train, verbose=1, epochs=300)
		# make a prediction on the test set
		yhat = model.predict(X_test)
		# round probabilities to class labels
		yhat = yhat.round()
		# calculate accuracy
		acc = accuracy_score(y_test, yhat)
		# store result
		print('>%.3f' % acc)
		results.append(acc)
	return results

In [ ]:
X_fp_train2=X_fp_train.dropna(axis=1)

X=X_fp_train2.astype('float64').values
y_np=y.astype('float64').values
print(X)
print(X_fp_train2)

print(X.shape)

[[ 1.13484916  0.90768744 -0.41638451 ...  0.          1.
   0.        ]
 [ 0.11928153  0.68173822  0.27239921 ...  0.          3.
   0.        ]
 [ 0.77997254  0.94646298  1.42534985 ...  0.          2.
   0.        ]
 ...
 [ 0.52514873  0.63122535  0.28817292 ...  1.          2.
   1.        ]
 [ 0.8164071   0.4176183   0.43163123 ...  0.          1.
   0.        ]
 [-1.24309611  1.56773029 -0.26957347 ...  0.          3.
   0.        ]]
       feature_0  feature_1  feature_2  ...  cp_type  cp_time  cp_dose
0       1.134849   0.907687  -0.416385  ...        0        1        0
1       0.119282   0.681738   0.272399  ...        0        3        0
2       0.779973   0.946463   1.425350  ...        0        2        0
3      -0.734910  -0.274641  -0.438509  ...        0        2        0
4      -0.452718  -0.477513   0.972316  ...        0        3        1
...          ...        ...        ...  ...      ...      ...      ...
23809   0.209361  -0.022389  -0.235888  ...        0       

In [ ]:
X=X_fp_train.astype('float64').values

display(X)
print(X.shape)

array([[ 1.13484916,  0.90768744, -0.41638451, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.11928153,  0.68173822,  0.27239921, ...,  0.        ,
         3.        ,  0.        ],
       [ 0.77997254,  0.94646298,  1.42534985, ...,  0.        ,
         2.        ,  0.        ],
       ...,
       [ 0.52514873,  0.63122535,  0.28817292, ...,  1.        ,
         2.        ,  1.        ],
       [ 0.8164071 ,  0.4176183 ,  0.43163123, ...,  0.        ,
         1.        ,  0.        ],
       [-1.24309611,  1.56773029, -0.26957347, ...,  0.        ,
         3.        ,  0.        ]])

(23814, 1563)


In [ ]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score

# evaluate model
X=X_fp_train.astype('float64').values
y_np=y.astype('float64').values


results = evaluate_model(X, y_np)


# summarize performance
print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

Epoch 1/300
670/670 [==============================] - 3s 4ms/step - loss: 0.0528 - logloss: 0.0491
Epoch 2/300
670/670 [==============================] - 3s 4ms/step - loss: 0.0226 - logloss: 0.0189
Epoch 3/300
670/670 [==============================] - 3s 5ms/step - loss: 0.0210 - logloss: 0.0176
Epoch 4/300
670/670 [==============================] - 3s 5ms/step - loss: 0.0202 - logloss: 0.0169
Epoch 5/300
670/670 [==============================] - 3s 5ms/step - loss: 0.0196 - logloss: 0.0164
Epoch 6/300
670/670 [==============================] - 3s 5ms/step - loss: 0.0192 - logloss: 0.0160
Epoch 7/300
670/670 [==============================] - 3s 4ms/step - loss: 0.0190 - logloss: 0.0158
Epoch 8/300
670/670 [==============================] - 3s 4ms/step - loss: 0.0187 - logloss: 0.0155
Epoch 9/300
670/670 [==============================] - 3s 4ms/step - loss: 0.0186 - logloss: 0.0154
Epoch 10/300
670/670 [==============================] - 3s 5ms/step - loss: 0.0184 - logloss: 0.0152

KeyboardInterrupt: ignored

# Q.E.D. 